- name: catalogue server configuration
  hosts: catalogue
  become: yes 
  tasks:
  - name: disable the default nodejs module and enable nodejs:1.18 version
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs 
    ansible.builtin.package:
      name: nodejs 
      state: present
    
  - name: add application user
    ansible.builtin.user:
      name: roboshop
    
  - name: remove app directory if exist already
    ansible.builtin.file:
      path: /app
      state: absent 
    
  - name: create a directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download application code 
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip
    
  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name : install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  
  - name: copy Catalogue service file 
    ansible.builtin.copy:
      src: catalogue.service 
      dest: /etc/systemd/system/
  
  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: start and enable catalogue 
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
