- name: catalogue configure
  hosts: catalogue
  tasks:
  - name: disable the default version and enable new 1.18 version nodejs
    ansible.builtin.command: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
    register: enable_status
  
  - name: enable module status
    ansible.builtin.debug:
      msg: 'enable status{{enable_status}}'
    
  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add user with name of roboshop
    ansible.builtin.user: 
      name: roboshop
    
  - name: create directory
    ansible.builtin.file:
    path: /app
    state: directory
  
  - name: Download application code 
    ansible.builtin.get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip

  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: change directory to app and install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
    
  - name: copy catalogue service 
    ansible.builtin.copy:
      src: catalogue.service 
      dest: /etc/systemd/system/catalogue.service

  - name: load the service
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: enable and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
      
  - name: copy mongodb repo 
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
    
  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  
  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/catalogue.js
    when: product_count.stdout == "0" # keep double quotes

  - name: enable and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes