- name: mongodb install and configuration
  hosts: mongodb
  become: yes 
  tasks:
  - name: setup the mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo 
      dest: /etc/yum.repos.d/
    
  - name: install mongodb 
    ansible.builtin.package:
      name: mongodb-org
      state: present
  
  - name: start and enable mongodb 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: update listen address from local host to others
    ansible.builtin.replace:
      path: /etc/mongod.conf
      after: '0.0.0.0'
      before: '127.0.0.1'
    
  - name: restart mongodb 
    ansible.builtin.service:
      name: mongod
      state: restarted

