- name: user server configuration
  hosts: user
  become: yes 
  tasks:
  - name: disable the default nodejs module and enable nodejs:1.18 version
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs 
    ansible.builtin.package:
      name: nodejs 
      state: present
    
  - name: add application user
    ansible.builtin.user:
      name: roboshop

  - name: remove app directory if exist already
    ansible.builtin.file:
      path: /app
      state: absent 
    
  - name: create a directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download application code 
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp/user.zip
    
  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name : install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user service file 
    ansible.builtin.copy:
      src: user.service 
      dest: /etc/systemd/system/user.service 
  
  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user 
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  
  - name: copy mongo-repo file 
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb client 
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
    
  - name: get the user count
    ansible.builtin.command:  mongo --host mongodb.royalreddy.co.in --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: gent user count 
    ansible.builtin.debug:
      msg: "user_count:{{user_count}}"

  - name: load schema
    ansible.builtin.command: mongo --host mongodb.royalreddy.co.in < /app/schema/user.js
    when: user_count.stdout == "0"

  - name: start and enable user 
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
