- name: Install web componets
  hosts: web 
  become: yes
  tasks: 
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove the default dir that web server is serving
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create html directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
    
  - name: download application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: copy roboshop configuration file 
    ansible.builtin.copy:
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restart nginx 
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
