- name: Install web componets
  hosts: web 
  become: yes
  tasks: 
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove the default dir that web server is serving
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create html directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory